### ISSUE TITLE
SiamFC++test问题，希望学长解答一下

### ISSUE THREAD

**Issue by Ruhao-Liu** [HonglinChu/SiamTrackers#17]
Traceback (most recent call last):
  File "./bin/my_test.py", line 66, in <module>
    tester.test()
  File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/engine/tester/tester_impl/vot.py", line 93, in test
    self.run_tracker()
  File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/engine/tester/tester_impl/vot.py", line 121, in run_tracker
    self.worker(keys, all_devs[0], result_queue, speed_queue)
  File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/engine/tester/tester_impl/vot.py", line 174, in worker
    lost, speed = self.track_single_video(tracker, video, v_id=v_id)
  File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/engine/tester/tester_impl/vot.py", line 238, in track_single_video
    package="vot_overlap").vot_overlap
  File "/home/c506/anaconda3/envs/siamfc/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/evaluation/vot_benchmark/pysot/utils/__init__.py", line 10, in <module>
    from . import region
ImportError: cannot import name 'region'
主要是不能加载SiamFC++/SiamFCpp-master/siamfcpp/evaluation/vot_benchmark/pysot/utils/__init__.py中的region模块
我用pycharm打开看了一下，好像是相对路径导入的问题，新手对这个问题不知道怎么解决，希望学长答复一下。谢谢

**Comment by HonglinChu** [comment]
你好，可以先在工程目录下运行 compile.sh 脚本文件
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 下午3:20
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] SiamFC++test问题，希望学长解答一下 (#17)





 
Traceback (most recent call last):
 File "./bin/my_test.py", line 66, in 
 tester.test()
 File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/engine/tester/tester_impl/vot.py", line 93, in test
 self.run_tracker()
 File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/engine/tester/tester_impl/vot.py", line 121, in run_tracker
 self.worker(keys, all_devs[0], result_queue, speed_queue)
 File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/engine/tester/tester_impl/vot.py", line 174, in worker
 lost, speed = self.track_single_video(tracker, video, v_id=v_id)
 File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/engine/tester/tester_impl/vot.py", line 238, in track_single_video
 package="vot_overlap").vot_overlap
 File "/home/c506/anaconda3/envs/siamfc/lib/python3.6/importlib/init.py", line 126, in import_module
 return _bootstrap._gcd_import(name[level:], package, level)
 File "", line 994, in _gcd_import
 File "", line 971, in _find_and_load
 File "", line 941, in _find_and_load_unlocked
 File "", line 219, in _call_with_frames_removed
 File "", line 994, in _gcd_import
 File "", line 971, in _find_and_load
 File "", line 955, in _find_and_load_unlocked
 File "", line 665, in _load_unlocked
 File "", line 678, in exec_module
 File "", line 219, in _call_with_frames_removed
 File "/home/c506/lrh/SiamFC++/SiamFCpp-master/siamfcpp/evaluation/vot_benchmark/pysot/utils/init.py", line 10, in 
 from . import region
 ImportError: cannot import name 'region'
 主要是不能加载SiamFC++/SiamFCpp-master/siamfcpp/evaluation/vot_benchmark/pysot/utils/init.py中的region模块
 我用pycharm打开看了一下，好像是相对路径导入的问题，新手对这个问题不知道怎么解决，希望学长答复一下。谢谢

**Comment by Ruhao-Liu** [comment]
谢谢学长，十分感谢

**Comment by Jeremy6666666** [comment]
同样的情况，运行完complie.sh文件，生成了一个.so文件。然后运行my_test.py仍然提示cannot import name "region",是需要建立一个链接么？恳请您帮忙解答一下，谢谢了！

**Comment by HonglinChu** [comment]
有这个提示说明你没有成功编译setup.py 文件，如果编译成功会生成region相关文件，关于setup文件的编译你可以参考pysot官方说明




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月21日(星期一) 晚上8:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HonglinChu/SiamTrackers] SiamFC++test问题，希望学长解答一下 (#17)





 
同样的情况，运行完complie.sh文件，生成了一个.so文件。然后运行my_test.py仍然提示cannot import name "region",是需要建立一个链接么？恳请您帮忙解答一下，谢谢了！
