### ISSUE TITLE
Windows下pycharm运行的，文件调用问题。  

### ISSUE THREAD

**Issue by AngeloTGU** [HonglinChu/SiamTrackers#42]
Traceback (most recent call last):
  File "K:/SiamTrackers-master/2-SiamFC/SiamFC-GOT/bin/my_test.py", line 8, in <module>
    from got10k.experiments import *
  File "K:\SiamTrackers-master\2-SiamFC\SiamFC-GOT\got10k\experiments\got10k.py", line 13, in <module>
    from ..datasets import GOT10k
ImportError: attempted relative import with no known parent package

我看前几天其实有人提问过这个问题，但是作者没有解答，我再提问一次。有人懂这个跨文件调用怎么出错了吗？应该1怎么改呀？

**Comment by HonglinChu** [comment]
1、看我B站代码演示视频，没有出现这个问题，检查一下是不是在项目根目录下运行的，注意项目根目录是 xxx/xxx/SiamFC-GOT，而不是xxx/SiamTrackers-master， 也不是xxx/SiamTrackers-master/2-SiamFC。

2、拿到代码，不建议直接在命令行运行。按照视频里面的操作，用VSCode或者Pycharm打开项目，确定配置好了虚拟环境，打开my_train.py , 修改你的模型加载路径、测试数据集路径，训练数据集路径。按F5（VSCode）进行调试，如果仍然出问题，可以私信我

3、如果运行中遇到报错，建议首先使用VSCode或者PyCharm进行单步调试
